### ISSUE TITLE
R: detect R markdown sites and set Connect's content_category

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1461] opened 2024-04-26 19:43 UTC

**Comment by jonkeane** [comment] 2024-12-07 16:07
@marcosnav is this handled with your work?

**Comment by marcosnav** [comment] 2024-12-09 13:44
@jonkeane Yes, the issue #1643 and this one refer to the same problem but are phrased differently. PR in review #2466 will fix this.

Closing since this one can be considered a duplicate of #1643

**Closed by marcosnav** 2024-12-09 13:44 UTC
