### ISSUE TITLE
Workbench: Deleting a `.posit` directory results in error

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2031] opened 2024-07-25 17:46 UTC
When deleting the `.posit` dir in Workbench after a deployment the UI throws this error:

> Failed to refresh files. An error has occurred at sendRefreshedFilesLists, files.getByConfiguration, StatusText=Not Found, Code=ERR_BAD_REQUEST, Msg=Request failed with status code 404, URL=http://localhost:34369/api/get//configurations/configuration-2/files

This does not seem to occur in other Linux environments.

**Comment by mmarchetti** [comment] 2024-07-26 15:29
Could this be a case where file watcher events were not triggered to reset the home view selection? 

Should the configuration files API return something different in the case where the named configuration can't be found?

**Comment by dotNomad** [comment] 2024-07-31 23:58
I'm getting a code smell of a race condition when I look into this. I'm not able to re-create locally, but I think it may be too fast at refreshing things. Unfortunately it is a bit hard to debug on workbench, but perhaps I can put some artificial delays in the code to attempt to reproduce.

**Comment by dotNomad** [comment] 2024-08-06 22:43
I haven't been able to reproduce this, but I still suspect there is a race condition here that could occur. I will bounce this back to triage to decide what to do.

**Comment by dotNomad** [comment] 2024-08-07 17:16
A large amount of file deletions seems to cause this as well - like deleting a large Python virtual environment.

Could be the same issue.

**Comment by dotNomad** [comment] 2024-08-07 17:21
After some discussion these sort of errors could be ignored. It is most likely because the config we have "selected" hasn't been updated when we get other file watcher events, but we will get to a good state after all file watcher events run.

Since we don't show the file list with nothing selected this error isn't particularly helpful.

**Comment by sagerb** [comment] 2024-08-27 16:19
Can we retest this, since we've merged a significant amount of changes/fixes to the file watcher and request code?

**Comment by dotNomad** [comment] 2024-08-29 22:35
Closing this one because it is done.

**Closed by dotNomad** 2024-08-29 22:35 UTC
Labels: bug, workbench, retest
